# Author: Sam Lyddon
# Date: 19/08/2019

version: '3'

services:
  notebook:
    build: .\
    image: 80-days-notebook
    container_name: 80-days-notebook
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=p
    volumes:
      - .:/home/jovyan/.
  db:
    image: postgres:latest
    container_name: 80-days-db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
     external: true